name: Publish Docker Image to GHCR

on:
  push:
    branches:
      - master
      - release/*
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push GPU Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.pb
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest-gpu
            ghcr.io/${{ github.repository }}:${{ github.sha }}-gpu
          build-args: |
            BASE_IMAGE=tensorflow/tensorflow:2.9.2-gpu

      - name: Build and push CPU Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.pb
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest-cpu
            ghcr.io/${{ github.repository }}:${{ github.sha }}-cpu
          build-args: |
            BASE_IMAGE=tensorflow/tensorflow:2.9.2
